services:
  mongodb:
    image: mongo:6.0
    container_name: auth_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
    container_name: auth_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
    command: npx ts-node src/app.ts
volumes:
  mongo_data: